// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFeypHcJhaCDK8ea6264ThJuk3ATy3z8w',
    appId: '1:61102233861:web:7984dd48aa1910f4a23f6c',
    messagingSenderId: '61102233861',
    projectId: 'bookingtable-d9cca',
    authDomain: 'bookingtable-d9cca.firebaseapp.com',
    storageBucket: 'bookingtable-d9cca.firebasestorage.app',
    measurementId: 'G-L90KVFYYRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Nt72QWT3qF5Vd6U_GkzRHB9NNGXiG74',
    appId: '1:61102233861:android:ce421cb8529578b3a23f6c',
    messagingSenderId: '61102233861',
    projectId: 'bookingtable-d9cca',
    storageBucket: 'bookingtable-d9cca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDLKw-g_79I2mmG9bBlaFb8QknXH99EL4',
    appId: '1:61102233861:ios:affc46a2b81f131ba23f6c',
    messagingSenderId: '61102233861',
    projectId: 'bookingtable-d9cca',
    storageBucket: 'bookingtable-d9cca.firebasestorage.app',
    androidClientId: '61102233861-4csski1m9b90f6sk2dp5ord98ifh007l.apps.googleusercontent.com',
    iosClientId: '61102233861-p6cnfl1784e88n3r3h1nc2364s42u41h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingTable',
  );
}
